In [1]:
import pandas as pd

ORIG_CSV_PATH = '/Users/lehacho/starry_sky/src/data/Catalogue.csv'
CLEAN_CSV_PATH = '/Users/lehacho/starry_sky/src/data/Catalogue_clean.csv'
df1 = pd.read_csv(ORIG_CSV_PATH)
df2 = pd.read_csv(CLEAN_CSV_PATH)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
df1

,StarID,HIP,HD,HR,Gliese,BayerFlamsteed,ProperName,RA,Dec,Distance,...,Mag,AbsMag,Spectrum,ColorIndex,X,Y,Z,VX,VY,VZ
0,0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.000005,...,-26.73,4.850000,G2V,0.656,0.00000,0.00000,0.00000,0.000000e+00,0.000000,0.000000e+00
1,1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000061,1.089013,282.485876,...,9.10,1.845016,F5,0.482,282.43485,0.00449,5.36884,4.900000e-08,-0.000007,-2.574000e-06
2,2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000253,-19.498837,45.662100,...,9.27,5.972221,K3V,0.999,43.04329,0.00285,-15.24144,-7.100000e-08,0.000040,-1.940000e-07
3,3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000334,38.859286,355.871886,...,6.61,-1.146468,B9,-0.019,277.11358,0.02422,223.27753,3.148000e-06,0.000009,-3.909000e-06
4,4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000559,-51.893546,129.032258,...,8.06,2.506509,F0V,0.370,79.62896,0.01164,-101.53103,7.200000e-08,0.000039,6.100000e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119612,119612,0.0,NaN,NaN,NN 4381,NaN,NaN,23.964046,38.631650,16.949153,...,12.64,11.494260,m,NaN,13.23968,-0.12462,10.58154,8.216000e-06,-0.000013,-1.043800e-05
119613,119613,0.0,NaN,NaN,NN 4385,NaN,NaN,23.995767,47.765021,16.722408,...,16.10,14.983506,m,1.870,11.24033,-0.01245,12.38117,1.272900e-05,0.000070,-1.148500e-05
119614,119614,0.0,NaN,NaN,NN 4386,NaN,NaN,23.996236,-44.071646,18.518519,...,12.82,11.481969,M7,1.640,13.30500,-0.01311,-12.88069,1.681600e-05,-0.000002,1.737200e-05
119615,119615,0.0,NaN,NaN,NN 4387,NaN,NaN,23.996723,-34.103312,12.820513,...,12.80,12.260473,M4,NaN,10.61573,-0.00910,-7.18829,-2.172300e-05,0.000045,-3.213800e-05
119616,119616,0.0,NaN,NaN,Gl 915,NaN,NaN,0.035492,-43.156625,7.800312,...,13.05,13.589440,DA5,0.070,5.68997,0.05287,-5.33537,-1.762200e-05,0.000023,-1.856600e-05

In [3]:
df2

            StarID         RA        Dec    Mag  ColorIndex
0       1010101010   2.400828   0.284654 -36.73       0.656
1                1   0.000061   1.089013   9.10       0.482
2                2   0.000253 -19.498837   9.27       0.999
3                3   0.000334  38.859286   6.61      -0.019
4                4   0.000559 -51.893546   8.06       0.370
...            ...        ...        ...    ...         ...
119612      119612  23.964046  38.631650  12.64       0.000
119613      119613  23.995767  47.765021  16.10       1.870
119614      119614  23.996236 -44.071646  12.82       1.640
119615      119615  23.996723 -34.103312  12.80       0.000
119616      119616   0.035492 -43.156625  13.05       0.070

[119617 rows x 5 columns]

In [4]:
df1.shape[0] == df2.shape[0]

True

In [12]:
df1.columns

Index(['StarID', 'HIP', 'HD', 'HR', 'Gliese', 'BayerFlamsteed', 'ProperName',
       'RA', 'Dec', 'Distance', 'PMRA', 'PMDec', 'RV', 'Mag', 'AbsMag',
       'Spectrum', 'ColorIndex', 'X', 'Y', 'Z', 'VX', 'VY', 'VZ'],
      dtype='object')

In [25]:
print(df1['ProperName'].unique())
print(df1['ProperName'].value_counts())

['Sol' nan 'Alpheratz' 'Caph' 'Algenib' 'Ankaa' 'Shedir' 'Diphda'
 '96 G. Psc' "Van Maanen's Star" 'Mirach' 'Achernar' 'p Eridani' 'Hamal'
 'Polaris' '268 G. Cet' 'Menkar' 'Algol' '82 G. Eri' 'Mirphak' 'Alcyone'
 'Aldebaran' "Kapteyn's Star" 'Rigel' 'Capella' 'Bellatrix' 'Alnath'
 'Nihal' 'Arneb' 'Alnilam' 'Alnitak' 'Saiph' 'Betelgeuse' 'Canopus'
 'Alhena' 'Sirius' 'Adhara' "Luyten's Star" 'Castor' 'Procyon' 'Pollux'
 'Alphard' 'Regulus' 'Groombridge 1618' 'Algieba' 'Merak' 'Lalande 21185'
 'Dubhe' 'Denebola' 'Groombridge 1830' 'Phad' 'Acrux' 'Alioth'
 'Vindemiatrix' 'Mizar' 'Spica' 'Alkaid' 'Hadar' 'Arcturus'
 'Proxima Centauri' 'Rigel Kentaurus B' 'Rigel Kentaurus A' 'Izar'
 'Kochab' '33 G. Lib' 'Alphekka' 'Unukalhai' 'Antares' 'Rasalgethi'
 'Shaula' 'Rasalhague' 'Etamin' "Barnard's Star" 'Kaus Australis' 'Vega'
 'Nunki' 'Tarazed' 'Altair' 'Deneb' 'Lacaille 8760' 'Alderamin' 'Enif'
 'Alnair' 'Kruger 60' 'Fomalhaut' 'Scheat' 'Markab' 'Lacaille 9352']
ProperName
Sol              1
Alkaid           1
33 G. Lib        1
Kochab           1
Izar             1
                ..
Arneb            1
Nihal            1
Alnath           1
Bellatrix        1
Lacaille 9352    1
Name: count, Length: 87, dtype: int64

In [26]:
df1['BayerFlamsteed'].unique()

array([nan, 'Tau Phe', 'The Oct', ..., '53Xi  UMa', 'Xi  Sco',
       '78Mu 2Cyg'], dtype=object)

In [27]:
df1['Gliese'].unique()

array([nan, 'GJ 1293', 'Wo 9848', ..., 'NN 4386', 'NN 4387', 'Gl 915'],
      dtype=object)

In [29]:
for col in ["ProperName", "BayerFlamsteed", "Gliese"]:
    df1[col] = df1[col].astype(str).str.strip()
    df1.loc[df1[col].isin(["nan", "NaN", "None", ""]), col] = pd.NA

has_any_name = df1[["ProperName", "BayerFlamsteed", "Gliese"]].notna().any(axis=1)

no_name_count = (~has_any_name).sum()
total_count = len(df1)

print(f"Всего звёзд: {total_count}")
print(f"Без ProperName, BayerFlamsteed и Gliese: {no_name_count}")
print(f"Это {no_name_count/total_count*100:.2f}% от каталога")

Всего звёзд: 119617
Без ProperName, BayerFlamsteed и Gliese: 113076
Это 94.53% от каталога

In [5]:
cols = ["HIP", "HD", "HR", "ProperName", "BayerFlamsteed", "Gliese"]

# На всякий случай убедимся, что типы ключей совпадают
df1["StarID"] = df1["StarID"].astype(df2["StarID"].dtype)

In [6]:
df2 = df2.merge(
    df1[["StarID"] + cols],   # берем только нужные колонки
    on="StarID",
    how="left"                # не теряем строки из df2
)

In [7]:
df2

,StarID,RA,Dec,Mag,ColorIndex,HIP,HD,HR,ProperName,BayerFlamsteed,Gliese
0,1010101010,2.400828,0.284654,-36.73,0.656,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.000061,1.089013,9.10,0.482,1.0,224700.0,NaN,NaN,NaN,NaN
2,2,0.000253,-19.498837,9.27,0.999,2.0,224690.0,NaN,NaN,NaN,NaN
3,3,0.000334,38.859286,6.61,-0.019,3.0,224699.0,NaN,NaN,NaN,NaN
4,4,0.000559,-51.893546,8.06,0.370,4.0,224707.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
119612,119612,23.964046,38.631650,12.64,0.000,0.0,NaN,NaN,NaN,NaN,NN 4381
119613,119613,23.995767,47.765021,16.10,1.870,0.0,NaN,NaN,NaN,NaN,NN 4385
119614,119614,23.996236,-44.071646,12.82,1.640,0.0,NaN,NaN,NaN,NaN,NN 4386
119615,119615,23.996723,-34.103312,12.80,0.000,0.0,NaN,NaN,NaN,NaN,NN 4387
119616,119616,0.035492,-43.156625,13.05,0.070,0.0,NaN,NaN,NaN,NaN,Gl 915

In [8]:
df2['HR'].dtype

dtype('float64')

In [ ]:
for c in ["HIP", "HD"]:
    df2[c] = pd.to_numeric(df2[c], errors="coerce")  # всё нечисловое -> NaN

# 2) Забиваем NaN нужными значениями
df2 = df2.fillna({
    "HIP": 0.0,
    "HD": 0.0,
    "HR": 0.0,
    "ProperName": "",
    "BayerFlamsteed": "",
    "Gliese": ""
})

# 3) Жёстко фиксируем типы
df2[["HIP", "HD"]] = df2[["HIP", "HD"]].astype("float64")
df2[["ProperName", "BayerFlamsteed", "Gliese"]] = (
    df2[["ProperName", "BayerFlamsteed", "Gliese"]].astype("string")  # pandas StringDtype
)

In [13]:
df2

,StarID,RA,Dec,Mag,ColorIndex,HIP,HD,ProperName,BayerFlamsteed,Gliese
0,1010101010,2.400828,0.284654,-36.73,0.656,0.0,0.0,,,
1,1,0.000061,1.089013,9.10,0.482,1.0,224700.0,,,
2,2,0.000253,-19.498837,9.27,0.999,2.0,224690.0,,,
3,3,0.000334,38.859286,6.61,-0.019,3.0,224699.0,,,
4,4,0.000559,-51.893546,8.06,0.370,4.0,224707.0,,,
...,...,...,...,...,...,...,...,...,...,...
119612,119612,23.964046,38.631650,12.64,0.000,0.0,0.0,,,NN 4381
119613,119613,23.995767,47.765021,16.10,1.870,0.0,0.0,,,NN 4385
119614,119614,23.996236,-44.071646,12.82,1.640,0.0,0.0,,,NN 4386
119615,119615,23.996723,-34.103312,12.80,0.000,0.0,0.0,,,NN 4387
119616,119616,0.035492,-43.156625,13.05,0.070,0.0,0.0,,,Gl 915

In [15]:
df2.to_csv('/Users/lehacho/starry_sky/src/data/Catalogue_clean_extd.csv', index=False)

In [16]:
df2.dtypes

StarID                     int64
RA                       float64
Dec                      float64
Mag                      float64
ColorIndex               float64
HIP                      float64
HD                       float64
ProperName        string[python]
BayerFlamsteed    string[python]
Gliese            string[python]
dtype: object